import { AppStatus, Application, Role, ServiceType, User } from './types';

export const TRANSLATIONS = {
  en: {
    title: 'PMRDA RTS Services Portal',
    subtitle: 'Pune Metropolitan Region Development Authority',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    citizen: 'Citizen',
    official: 'Official',
    admin: 'Admin',
    services: 'Our Services',
    trackStatus: 'Track Application Status',
    dashboard: 'Dashboard',
    apply: 'Apply for Service',
    myApps: 'My Applications',
    newApp: 'New Application',
    submit: 'Submit',
    cancel: 'Cancel',
    approve: 'Approve',
    reject: 'Reject',
    clarify: 'Request Clarification',
    status: 'Status',
    sla: 'SLA Days',
    action: 'Action',
    welcome: 'Welcome',
    reports: 'Reports',
    manageUsers: 'Manage Users',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    enterAppId: 'Enter Application ID',
    track: 'Track',
    uploadDocs: 'Upload Documents',
    selectService: 'Select Service',
    // Auth
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    mobile: 'Mobile Number',
    department: 'Department',
    designation: 'Designation',
    alreadyAccount: 'Already have an account?',
    noAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    demoCreds: 'Demo Credentials',
    officialPortal: 'Official Portal',
    citizenPortal: 'Citizen Portal',
    adminPortal: 'Admin Portal',
    accessPortal: 'Access Portal',
    passwordMismatch: 'Passwords do not match',
    fillAllFields: 'Please fill all required fields',
  },
  mr: {
    title: 'पीएमआरडीए आरटीएस सेवा पोर्टल',
    subtitle: 'पुणे महानगर प्रदेश विकास प्राधिकरण',
    login: 'लॉगिन',
    register: 'नोंदणी करा',
    logout: 'बाहेर पडा',
    citizen: 'नागरिक',
    official: 'अधिकारी',
    admin: 'प्रशासक',
    services: 'आमच्या सेवा',
    trackStatus: 'अर्ज स्थिती तपासा',
    dashboard: 'डॅशबोर्ड',
    apply: 'सेवेसाठी अर्ज करा',
    myApps: 'माझे अर्ज',
    newApp: 'नवीन अर्ज',
    submit: 'सादर करा',
    cancel: 'रद्द करा',
    approve: 'मंजूर',
    reject: 'नाकारले',
    clarify: 'स्पष्टीकरण मागवा',
    status: 'स्थिती',
    sla: 'एस.एल.ए दिवस',
    action: 'कृती',
    welcome: 'स्वागत आहे',
    reports: 'अहवाल',
    manageUsers: 'वापरकर्ते व्यवस्थापित करा',
    pending: 'प्रलंबित',
    approved: 'मंजूर',
    rejected: 'नाकारले',
    enterAppId: 'अर्ज क्रमांक प्रविष्ट करा',
    track: 'ट्रॅक करा',
    uploadDocs: 'कागदपत्रे अपलोड करा',
    selectService: 'सेवा निवडा',
    // Auth
    email: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्डची पुष्टी करा',
    fullName: 'पूर्ण नाव',
    mobile: 'मोबाईल क्रमांक',
    department: 'विभाग',
    designation: 'पद',
    alreadyAccount: 'आधीच खाते आहे?',
    noAccount: 'खाते नाही?',
    signUp: 'साइन अप करा',
    signIn: 'साइन इन करा',
    demoCreds: 'डेमो क्रेडेंशियल्स',
    officialPortal: 'अधिकारी पोर्टल',
    citizenPortal: 'नागरिक पोर्टल',
    adminPortal: 'प्रशासक पोर्टल',
    accessPortal: 'पोर्टलवर जा',
    passwordMismatch: 'पासवर्ड जुळत नाहीत',
    fillAllFields: 'कृपया सर्व आवश्यक फील्ड भरा',
  }
};

export const MOCK_SERVICES: ServiceType[] = [
  { id: '1', nameEn: 'Building Permission', nameMr: 'बांधकाम परवानगी', description: 'Approval for new construction' },
  { id: '2', nameEn: 'Land Zone Certificate', nameMr: 'जमीन विभाग प्रमाणपत्र', description: 'Zone verification certificate' },
  { id: '3', nameEn: 'NOC for Fire', nameMr: 'अग्नी ना हरकत प्रमाणपत्र', description: 'Fire safety compliance' },
  { id: '4', nameEn: 'Layout Approval', nameMr: 'अभ्यासक्रम मंजूरी', description: 'Plotting layout approval' },
];

export const MOCK_APPLICATIONS: Application[] = [
  { id: 'APP-2023-001', serviceId: '1', applicantName: 'Rajesh Kumar', submissionDate: '2023-10-20', status: AppStatus.SUBMITTED, slaDaysRemaining: 15, documents: ['plan.pdf', '7-12.pdf'] },
  { id: 'APP-2023-002', serviceId: '2', applicantName: 'Anita Desai', submissionDate: '2023-10-18', status: AppStatus.IN_PROGRESS, slaDaysRemaining: 5, documents: ['zone_req.pdf'] },
  { id: 'APP-2023-003', serviceId: '1', applicantName: 'Suresh Patil', submissionDate: '2023-10-15', status: AppStatus.APPROVED, slaDaysRemaining: 0, documents: ['final_plan.pdf'] },
  { id: 'APP-2023-004', serviceId: '3', applicantName: 'Tech Park Ltd', submissionDate: '2023-10-21', status: AppStatus.CLARIFICATION, slaDaysRemaining: 12, documents: ['safety_audit.pdf'], remark: 'Upload updated fire plan' },
];

export const MOCK_OFFICIALS: User[] = [
  { id: 'OFF-1', name: 'Officer Deshmukh', role: Role.OFFICIAL, department: 'Town Planning' },
  { id: 'OFF-2', name: 'Officer Kulkarni', role: Role.OFFICIAL, department: 'Fire Safety' },
];